# Generated by Django 5.2.13 on 2026-05-05 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portal_member_id', models.CharField(db_index=True, max_length=255)),
                ('portal_domain', models.CharField(max_length=255)),
                ('created_by_b24_user_id', models.IntegerField()),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('contact', 'Contact'), ('company', 'Company'), ('deal', 'Deal'), ('task', 'Task')], max_length=32)),
                ('source_format', models.CharField(choices=[('xlsx', 'XLSX'), ('xls', 'XLS'), ('csv', 'CSV')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('uploaded', 'Uploaded'), ('validated', 'Validated'), ('ready', 'Ready'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('original_filename', models.CharField(max_length=255)),
                ('upload_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_sheet_name', models.CharField(blank=True, max_length=255)),
                ('data_start_row', models.PositiveIntegerField(default=2)),
                ('header_row', models.PositiveIntegerField(default=1)),
                ('total_rows', models.PositiveIntegerField(blank=True, null=True)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('import_settings', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'import_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portal_member_id', models.CharField(db_index=True, max_length=255)),
                ('portal_domain', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('contact', 'Contact'), ('company', 'Company'), ('deal', 'Deal'), ('task', 'Task')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('mapping_schema', models.JSONField(default=dict)),
                ('column_settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'import_template',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('portal_member_id', 'entity_type', 'name'), name='uniq_import_template_per_portal_entity_name')],
            },
        ),
    ]
