# Generated by Django 5.2.13 on 2026-05-05 10:12

import importer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='file_size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importsession',
            name='stored_file',
            field=models.FileField(blank=True, upload_to=importer.models.import_session_upload_to),
        ),
    ]
