# Generated by Django 5.2.13 on 2026-05-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_importsession_file_size_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='preview_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
