# Generated by Django 5.2.13 on 2026-05-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0003_importsession_preview_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="importtemplate",
            name="dedup_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
