# Generated by Django 5.2.13 on 2026-05-06 11:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0004_importtemplate_dedup_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImporterUserRole",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("portal_member_id", models.CharField(db_index=True, max_length=255)),
                ("portal_domain", models.CharField(max_length=255)),
                ("b24_user_id", models.IntegerField()),
                ("role", models.CharField(choices=[("operator", "Operator"), ("viewer", "Viewer")], max_length=32)),
                ("granted_by_b24_user_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "importer_user_role",
                "ordering": ["b24_user_id"],
                "constraints": [
                    models.UniqueConstraint(fields=("portal_member_id", "b24_user_id"), name="uniq_importer_role_per_portal_user"),
                ],
            },
        ),
    ]
