# Generated by Django 5.2.14 on 2026-05-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0009_user_department_entity_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsession',
            name='entity_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('contact', 'Contact'), ('company', 'Company'), ('deal', 'Deal'), ('linked_company_contact', 'Linked company + contact'), ('task', 'Task'), ('task_comment', 'Task comment'), ('task_checklist_item', 'Task checklist item'), ('task_attachment', 'Task attachment'), ('crm_files_lead', 'CRM files: Lead'), ('crm_files_contact', 'CRM files: Contact'), ('crm_files_company', 'CRM files: Company'), ('crm_files_deal', 'CRM files: Deal'), ('user', 'User'), ('department', 'Department')], max_length=32),
        ),
        migrations.AlterField(
            model_name='importtemplate',
            name='entity_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('contact', 'Contact'), ('company', 'Company'), ('deal', 'Deal'), ('linked_company_contact', 'Linked company + contact'), ('task', 'Task'), ('task_comment', 'Task comment'), ('task_checklist_item', 'Task checklist item'), ('task_attachment', 'Task attachment'), ('crm_files_lead', 'CRM files: Lead'), ('crm_files_contact', 'CRM files: Contact'), ('crm_files_company', 'CRM files: Company'), ('crm_files_deal', 'CRM files: Deal'), ('user', 'User'), ('department', 'Department')], max_length=32),
        ),
    ]
